### ISSUE TITLE
Replace 'then' with other keyword

### ISSUE THREAD

**Issue by sureshjoshi** [ZamzamInc/ZamzamKit#1]
'then' is generally assumed to be a part of Promises, so using it in an initializer might be confusing (and it could cause a collision at some point).

Kotlin (unfortunately) has about 5 operators which act similarly, and can be used for this kind of initialization: http://beust.com/weblog/2015/10/30/exploring-the-kotlin-standard-library/

Let, Run, With, Apply, Use

'With' is the most similarly applicable. 

C# and sorta Java, it's built into the language, and Ruby has tap (https://stackoverflow.com/questions/34956711/one-step-object-creation-and-property-initialization-in-swift)

**Comment by basememara** [comment]
Awesome suggestion! The `with` API always had a nice ring to it and perfect that it matches Kotlin. Updated at https://github.com/ZamzamInc/ZamzamKit/commit/4b3a0d105bd7e2b9088046e2f13271743c279269.

**Comment by sureshjoshi** [comment]
So, in hindsight - it might be closer to 'apply' because it returns the original object?

https://medium.com/@tpolansk/the-difference-between-kotlins-functions-let-apply-with-run-and-else-ca51a4c696b8

These are so hard to keep track of. I wish they dropped this to only 2-3 of these functions

**Comment by sureshjoshi** [comment]
Oh, wait, that might be wrong again..... 

Apply makes the object unnecessary, Also might be more correct (but I would never name an operator 'also'). 

            val args = Bundle()
            args.putString(...)
            args.putInt(...)
            // args is a Bundle

            val args = Bundle().apply {
                putString(...)
                putInt(...)
                123
            }
            // args is a Bundle
            
            val args = Bundle().also { 
                it.putString(...)
                it.putInt(...)
                123
            }
            // args is a Bundle
            
            val args = with(Bundle()) {
                putString(...)
                putInt(...)
                123
            }
            // args is an Integer

**Comment by basememara** [comment]
Ya `apply` crossed my mind too, but coming from JavaScript, it felt really funny and makes you think you're working with a function.

Also `with` apparently is a keyword in Scala that let's you mixin traits which is kinda similar: https://stackoverflow.com/questions/6761534/scala-with-keyword-usage
