### ISSUE TITLE
CLKComplicationServer is unavailable in iOS

### ISSUE THREAD

**Issue by Najmeh-Myant** [ZamzamInc/ZamzamKit#27]
XCode 12 

SourcePackages/checkouts/ZamzamKit/Sources/ZamzamUI/Views/WatchKit/Extensions/CLKComplicationServer.swift:13:18: ‘CLKComplicationServer’ is unavailable in iOS

**Comment by KaneDenzilMyant** [comment]
Please provide more information on the issue. :man-facepalming::skin-tone-2:

**Comment by carbonimax** [comment]
You can replace `#if canImport(ClockKit)` by `#if os(watchOS)` and it compiles.

**Comment by Najmeh-Myant** [comment]
Thank you @carbonimax 
I actually reverted my XCode to 11.7 and it went away. It only happens with XCode 12.
I will try your suggestion when I went back to XCode 12.
