### ISSUE TITLE
Generic type 'Result' specialized with too few type parameters (got 1, but expected 2)

### ISSUE THREAD

**Issue by Rubenfer** [ZamzamInc/ZamzamKit#3]
I'm using ZamzamKit in one Swift project and I have this problem when I use this function

Error:
Generic type 'Result' specialized with too few type parameters (got 1, but expected 2)

Functions:
public func ...(..., completion: ((ZamzamKit.Result<RemotePostResults>) -> Void)? = nil) -> ... {
...
}

How can I solve it?

Best regards.

**Comment by zhenjiangliu24** [comment]
`public func ...(..., completion: ((ZamzamKit.Result<Void>) -> Void)? = nil) -> ... {
...
}`

**Comment by Rubenfer** [comment]
Still without working. The error that I have is Generic type 'Result' specialized with too few type arguments (for 1, but expected 2).

I use ZamzamKit.Result<RemotePostResults>

That I don't know is how to implement the ErrorType, because in the documentation the declaration is Result<Value, ErrorType> where ErrorType:Error. 

Please, can you help me?

Thanks!

**Comment by basememara** [comment]
Sorry there was a change to `Result` that requires you to specify an `ErroryType` (https://github.com/ZamzamInc/ZamzamKit/commit/5f2896ae41c4c92802b24a09da9526673090902e):

```
enum DataError: Error {
    case duplicateFailure
    case nonExistent
    case incomplete
}

func myFunc(id: Int, completion: ((Result<Void, DataError>) -> Void)? = nil) {
  ...
}
```

The reason is a strongly defined error allowed more reliable error handling by the caller. So now you can do something like this:

```
myFunc(id: 123) {
  guard $0.isSuccess else {
    switch $0.error {
    case .duplicateFailure?: //do something
    case .nonExistent?: //do something else
    case .incomplete?: //do something else
    case nil: //generic alert or something
    }

    return
  }
}
```

**Comment by Rubenfer** [comment]
Now I have this:

`enum DataError: Error {
case duplicateFailure
case nonExistent
case incomplete
}`
and this function:
`func ... (...,completion:((ZamzamKit.Result<RemotePostResults,DataError>) -> Void)? = nil) -> ... {
...
}`
but now I have a linea that is:
`completion?(.failure(response.result.error ?? PressError.general))`
and in this line I have the error

> Member 'failure' in 'Result<RemotePostResults, PostService.DataError>' produces result of type 'Result<Value, ErrorType>', but content expects 'Result<RemotePostResults,PostService.DataError>'

Thanks one more time!

**Comment by basememara** [comment]
You're trying to mix up error types. What you want to do is have a single `Error` type for the caller and provide an inner error if available:

```
enum DataError: Error {
    case duplicateFailure
    case nonExistent
    case incomplete
    case other(Error?)
}

...

...completion?(.failure(response.result.error ?? DataError.other(PressError.general)))

...

myFunc(id: 123) {
  guard $0.isSuccess else {
    switch $0.error {
    case .duplicateFailure?: //do something
    case .nonExistent?: //do something else
    case .incomplete?: //do something else
    case .other(let error)?: //alert("There was an internal error: \(error?.localizedDescription)"
    case nil: //generic alert or something
    }

    return
  }
}
```
You can even add error conversion extensions for convenience:
```
extension DataError {
    
    init?(from error: PressError?) {
        switch error {
        case .incomplete?: self = .incomplete
        case .unauthorized?: self = .unauthorized
        ...
        default: self = .other(error)
        }
    }
}

...completion?(.failure(response.result.error ?? DataError(from: .general)))
```
I hope this helps. Let me know if you have any other problems or suggestions.

**Comment by Rubenfer** [comment]
Solved with ZamzamKit v.1.3

Thanks for your time
