### ISSUE TITLE
NSDate new API support - Swift 4.0.3

### ISSUE THREAD

**Issue by megatcorleone** [ZamzamInc/ZamzamKit#4]
Hi, i am stucked with **DateTimeHelper** class which is i installed the framework from Cocoapod.
Sorry i am beginner with the Swift APIs. I tried already using the fix-helper (Xcode 9) to the some of the code in frameworks. I am working on this  : 

`    public func incrementDay(date: Date = Date(), numberOfDays: Int = 1) -> Date {
        Calendar.current.component(byAdding: .Day, value: numberOfDays, from: date, options: [])!`

The problem is on the addingByUnit method which outputs error : 

> Extra argument 'value' in call

Appreciate your help!

**Comment by basememara** [comment]
Please try to update the pod, I've uploaded a new pod spec that should correct the issue.
