### ISSUE TITLE
Carthage fails to build

### ISSUE THREAD

**Issue by ThorinHanson** [ZamzamInc/ZamzamKit#6]
Using the latest xcode-beta and swift 4.2 I am getting the following:

`*** Fetching ZamzamKit
*** Checking out ZamzamKit at "2.1.1"
*** xcodebuild output can be found in /var/folders/jc/vvl5tz5d1dvbr76dt3w8p8wr0000gn/T/carthage-xcodebuild.QBwkB3.log
*** Building scheme "ZamzamKit iOS" in ZamzamKit.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/thanson/Projects/marketplace/Carthage/Checkouts/ZamzamKit/ZamzamKit.xcworkspace -scheme ZamzamKit\ iOS -configuration Release -derivedDataPath /Users/thanson/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L232m/ZamzamKit/2.1.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jc/vvl5tz5d1dvbr76dt3w8p8wr0000gn/T/ZamzamKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/thanson/Projects/marketplace/Carthage/Checkouts/ZamzamKit)
`

**Comment by basememara** [comment]
Apologies for the delay, I've updated the project to Swift 4.2 and Xcode. Please reopen if there's still an issue.
