### ISSUE TITLE
SynchronizedArray crashes during debug sessions...

### ISSUE THREAD

**Issue by Lord-Kamina** [ZamzamInc/ZamzamKit#9]
I'm not really sure whether this is a fault in your code or a bug in Swift but I've realized that the line
``` swift
private let queue = DispatchQueue(label: "\(DispatchQueue.labelPrefix).SynchronizedArray", attributes: .concurrent)
```
Crashes debug sessions inside XCode. The code works perfectly on its own but if I'm debugging inside XCode, there's always a `EXC_BAD_ACCESS (code=1, address=0x10)` when that line is reached.

Any idea what could be the issue?

**Comment by basememara** [comment]
Thanks for reporting this. Do you have a small sample where I can reproduce this? I haven't seen this.

Maybe you want to try removing the string interpolation `\(DispatchQueue.labelPrefix)` to see if that has anything to do with it?

**Comment by Lord-Kamina** [comment]
> Maybe you want to try removing the string interpolation \(DispatchQueue.labelPrefix) to see if that has anything to do with it?

It doesn't; I was originally using the old version from your blog post and the issue was also present.


https://github.com/Lord-Kamina/SwiftDefaultApps/blob/864d012bbc92b1f709b51d874f5430e517697c14/Sources/Prefpane%20Sources/Model/SWDAHandlersModel.swift#L47
Here's the function from where I'm instantiating SynchronizedArrays; I wrote that a while ago and had forgotten about the coercion from `Any`. Maybe that has to do with it?

**Comment by basememara** [comment]
I looked at the code and there are many forced unwrappings there. I’d try to fixing those first and see if that helps. If you force cast it to the wrong type and append or retrieve an element, I’d imagine a bad access would occur in that case. How about making all elements share a protocol instead switching between multiple array types?

**Comment by Lord-Kamina** [comment]
The forced unwrappings are pretty definitely not the issue; among other things because the error occurs during initialization.

Anyway, it seems the error is not in your code either. I was able to reproduce the issue in a new project (without zamzamkit) by initializing a DispatchQueue and running the debugger inside XCode.

Can you confirm this please so I can rule out something being corrupted in my machine?
